class LegalContent {
  static const String privacyPolicy = """
# Privacy Policy
Last updated: April 19, 2026

At FinTrack Pro, we take your privacy seriously. This document explains how we handle your data.

## 1. Data Collection
FinTrack Pro is designed to be a "Privacy First" application. By default, all your financial transactions and category data are stored strictly on your local device.

## 2. Local Storage
We use encrypted local storage to save your transaction history, account balances, and application preferences. This data never leaves your device unless you explicitly enable cloud synchronization features.

## 3. Third-Party Services
If you choose to use optional cloud features, your data may be processed via Firebase (Google Cloud). In such cases, your data is protected by industry-standard encryption and security protocols.

## 4. Analytics
We may collect anonymous usage statistics to improve application performance. This data does not contain any personal financial information or transaction details.

## 5. Your Rights
You have the total right to your data. You can delete all your data at any time via the "Data Management" section in Settings.
""";

  static const String termsConditions = """
# Terms & Conditions
Last updated: April 19, 2026

By using FinTrack Pro, you agree to the following terms.

## 1. Financial Disclaimer
FinTrack Pro is a tool for personal expense tracking and financial management. It does NOT provide financial, tax, or legal advice. Always consult with a professional for financial planning.

## 2. Accuracy of Data
You are responsible for the accuracy of the data you enter. FinTrack Pro is not liable for any financial decisions made based on reports generated by the app.

## 3. Data Loss
While we use robust local storage mechanisms, we are not responsible for any data loss occurring due to device failure, app uninstallation without backup, or hardware damage.

## 4. License
We grant you a personal, non-exclusive license to use this app for personal use. Commercial redistribution or reverse engineering is prohibited.
""";

  static const String dataSafety = """
# Data Safety Section
How we handle your sensitive information.

## Encryption
Everything you enter into FinTrack Pro is stored using secure local databases. Sensitive transaction amounts and descriptions are handled with standard encryption providers where applicable.

## No Unauthorized Access
We do not sell, trade, or share your financial data with any third parties. Your financial life remains your own.

## Data Control
- **Manual Deletion**: You can purge all data instantly.
- **No Invisible Sync**: We will never sync your data to a cloud without your explicit consent and login.
- **Portability**: You have full control over your recorded history.
""";
}
